//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string User_Preferences { get; set; }
        public string Image { get; set; }
    }
}
